name: 'DigitalOcean Registry Prune'
description: 'Prunes old tags from a container registry on digital ocean'
author: 'PierreAndreis'
inputs:
  token: # change this
    required: true
    description: 'Digital Ocean Token with write permission'
  quiet: 
    required: false
    description: 'Do not display a table with pruned versions'
    default: "false"
  disableGc: 
    required: false
    description: 'Do not start garbage-collection after'
    default: "false"
runs:
  using: 'node12'
  main: 'dist/index.js'
